### ISSUE TITLE
Deleting files shouldn't crash the plugin

### ISSUE THREAD

**Issue by gaearon** [Urthen/case-sensitive-paths-webpack-plugin#8]
I noticed that if I delete a folder while WebpackDevServer is running, this plugin crashes the process:

```
Compiling...
/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/webpack-core/lib/NormalModuleMixin.js:151
				throw e;
				^

Error: ENOENT: no such file or directory, scandir '/Users/dan/p/redux/examples/async/src/store'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at CaseSensitivePathsPlugin.getFilenamesInDir (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/case-sensitive-paths-webpack-plugin/index.js:45:19)
    at CaseSensitivePathsPlugin.fileExistsWithCaseSync (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/case-sensitive-paths-webpack-plugin/index.js:63:26)
    at NormalModuleFactory.<anonymous> (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/case-sensitive-paths-webpack-plugin/index.js:109:34)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/tapable/lib/Tapable.js:86:13)
    at onDoneResolving (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:726:13
    at /Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:236:30)
    at _parallel (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:731:9)
    at /Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/webpack/lib/NormalModuleFactory.js:109:12
    at /Users/dan/p/redux/examples/async/node_modules/react-scripts/node_modules/async/lib/async.js:726:13
```

**Comment by Urthen** [comment]
Fixed in 1.1.3. Thanks!
